version: "3"

services:
  spiderfoot-full:
    build:
      context: ./
      dockerfile: ./Dockerfile.full
    volumes:
      - ../files/spiderfoot-full-data:/var/lib/spiderfoot

volumes:
  spiderfoot-full-data: